### ISSUE TITLE
Issues with Heroku/packages.graylog2.org?

### ISSUE THREAD

**Issue by zacharinas** [Graylog2/fpm-recipes#11]
Hello, been getting this error all afternoon.  Sometimes as soon as I run the apt-get install it will say "0% [Working]" and hang there.  Other times the download will start but take a very long time (internet connection here tests at 20Mbps).

Just wasn't sure if there might be a known issue or if I need to check something on my end.

:~$ sudo apt-get install graylog2-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  graylog2-server
0 upgraded, 1 newly installed, 0 to remove and 44 not upgraded.
Need to get 66.2 MB of archives.
After this operation, 74.6 MB of additional disk space will be used.
Get:1 https://packages.graylog2.org/repo/debian/ trusty/0.90 graylog2-server all 0.90.0-1 [66.2 MB]
Fetched 66.2 MB in 10min 25s (106 kB/s)
E: Failed to fetch https://packages.graylog2.org/repo/debian/pool/trusty/0.90/g/graylog2-server/graylog2-server_0.90.0-1_all.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by anujith-singh** [comment]
I have the exact same issue
@zacharinas could you figure out a solution for this?

**Comment by anujith-singh** [comment]
Worked after few attempts
