### ISSUE TITLE
RHEL9 and repository signing for Graylog Sidecar (SHA1 crypto)

### ISSUE THREAD

**Issue by SalC3** [Graylog2/fpm-recipes#119]
When trying to install the Graylog Sidecar 1.2.0-1 from the repository on RHEL9 it was failing with “Error: GPG check FAILED” after installing the repository RPM. I tried ignoring the GPG check (yum --nogpgcheck install graylog-sidecar) however that failed with “package graylog-sidecar-1.2.0-1.x86_64 does not verify: Header V4 RSA/SHA1 Signature, key ID b1606f22: BAD”

I determined that in RHEL9 they disabled weaker crypto methods.  One option is to download the .rpm directly instead of using the repository, but if using the repository is desired, a temporary workaround is to modify the crypto policy for the system and then reboot:

    update-crypto-policies --set DEFAULT:SHA1

RHEL article on this here:
https://access.redhat.com/articles/6846411

Forum link to Graylog Community discussion:
https://community.graylog.org/t/collector-sidecar-for-rhel-9/24330

**Comment by bernd** [comment]
Thank you for the report. We must figure out how to migrate the package signing without breaking updates for everyone. :slightly_smiling_face:

**Comment by bernd** [comment]
This will be fixed with the upcoming 1.3.0 release. Thanks for the report!
