### ISSUE TITLE
Graylog 5.0 *-plugin packages did not update from alpha to beta

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/fpm-recipes#120]
In a Debian 11 installation, on upgrading from Graylog 5.0 alpha to beta1 via apt, the packages for *-plugin are still on the alpha version.

> root@gl50alpha-lab:/usr/share/graylog-server/plugin# dpkg -l | grep graylog
> ii  graylog-5.0-repository                  1-1                            all          Package to install Graylog 5.0 GPG key and repository
> ii  graylog-enterprise-integrations-plugins 5.0.0-1.alpha.1                all          Graylog Enterprise Integrations plugins
> ii  graylog-enterprise-plugins              5.0.0-1.alpha.1                amd64        Graylog Enterprise plugins
> ii  graylog-server                          5.0.0-2.beta.1                 amd64        Graylog server
> 
> root@gl50alpha-lab:/usr/share/graylog-server/plugin# apt update && apt upgrade
> Hit:1 http://deb.debian.org/debian bullseye InRelease
> Get:2 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
> Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
> Ign:5 http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 InRelease
> Hit:6 http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 Release
> Hit:4 https://packages.graylog2.org/repo/debian stable InRelease
> Fetched 44.1 kB in 1s (34.1 kB/s)
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Calculating upgrade... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> root@gl50alpha-lab:/usr/share/graylog-server/plugin#

Apt history shows that `graylog-integrations-plugins:amd64 (5.0.0-1.alpha.1)` was removed:

> Start-Date: 2022-10-27  07:00:42
> Commandline: apt-get -u dist-upgrade
> Requested-By: damian (1000)
> Install: mongodb-mongosh:amd64 (1.6.0, automatic), mongodb-org-database:amd64 (5.0.13, automatic)
> Upgrade: graylog-server:amd64 (5.0.0-1.alpha.1, 5.0.0-2.beta.1), mongodb-org:amd64 (4.4.17, 5.0.13)
> Remove: graylog-integrations-plugins:amd64 (5.0.0-1.alpha.1)
> End-Date: 2022-10-27  07:02:28

**Comment by bernd** [comment]
This issue is fixed in the latest pre-release OS packages for 5.0.
