### ISSUE TITLE
Graylog Sidecar: repo is arch all, but Sidecar itself is amd64 only

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/fpm-recipes#128]
@darneymartin and I encountered issues trying to install graylog-sidecar on his company-provided MBP inside an Ubuntu Docker container. 

We noted that the Sidecar repo package is arch all:

> damian@damian-scp-dev:$ dpkg --info graylog-sidecar-repository_1-5_all.deb
>     new Debian package, version 2.0
>     size 1986 bytes: control archive=535 bytes. 
>          96 bytes,     2 lines      conffiles
>         304 bytes,    11 lines      control
>         250 bytes,     3 lines      md5sums
>     Package: graylog-sidecar-repository
>     Version: 1-5
>     License: SSPL
>     Vendor: graylog
>     Architecture: all
>     Maintainer: Graylog, Inc. <hello@graylog.org>
>     Installed-Size: 0
>     Section: optional
>     Priority: optional
>     Homepage: https://www.graylog.org/
>     Description: Package to install Graylog Sidecar GPG key and repository. 

However, the Sidecar package itself is amd64:

> damian@damian-scp-dev:~$ dpkg --info graylog-sidecar_1.4.0-2_amd64.deb
>  new Debian package, version 2.0.
>  size 3025322 bytes: control archive=491 bytes.
>       33 bytes,     1 lines      conffiles
>      265 bytes,    11 lines      control
>      201 bytes,     3 lines      md5sums
>  Package: graylog-sidecar
>  Version: 1.4.0-2
>  License: SSPL
>  Vendor: graylog
>  Architecture: amd64
>  Maintainer: Graylog, Inc. <hello@graylog.org>
>  Installed-Size: 7127
>  Section: optional
>  Priority: optional
>  Homepage: https://graylog.org
>  Description: Graylog collector sidecar

And the binary itself is indeed x64:

> $ file /usr/bin/graylog-sidecar
> /usr/bin/graylog-sidecar: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped

However, this prompted confusion when Darnell tried to install graylog-sidecar in the Docker container on his Apple Silicon Mac, as `apt-get install graylog-sidecar` would just return a message that the package couldn't be find, as there were no arm64/aarch64 matches for the graylog-sidecar package. Darnell forced the Docker container to amd64, and he was able to install the package without further issue. 

It's possible that customers may be trying to do this on their own ARM-powered systems, e.g. AWS EC2 ARM instances, and encounter the same confusion.

**Comment by bernd** [comment]
This should be fixed in 1.5.0. Please check and re-open if it's still an issue.
