### ISSUE TITLE
Declare integrations_scripts_dir regardless of presence of enterprise plugins

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/fpm-recipes#136]
This is to address edge cases where `server.conf` may be missing this configuration: https://github.com/Graylog2/graylog-plugin-enterprise/issues/7616

Because there is no default value, it can lead to unexpected and unwanted (and undocumented) behavior. We do (wrongly) document `server.conf` having a default value when in actuality it doesn't, or its default value is conditional on `server.conf` being created from the enterprise install package.

I think an elegant solution to this is to just include this config for all installs such as `graylog-server` in addition to `graylog-enterprise`

```
integrations_scripts_dir = /usr/share/graylog-server/scripts
```

**Comment by tellistone** [comment]
For this one, just need to add that line of config to be included in server.conf by default

**Comment by patrickmann** [comment]
@tellistone Is this a build issue, since it is filed in the FPM repo? 
Also confused by [this](https://github.com/Graylog2/graylog-plugin-enterprise/issues/7616#issuecomment-2214214963) comment, from the same day that the issue was filed.

**Comment by drewmiranda-gl** [comment]
I believe the intention is to have `recipes/graylog-server/patches/graylog-server.conf.patch`

include `+integrations_scripts_dir = /usr/share/graylog-server/scripts` the same as `recipes/graylog-enterprise/patches/graylog-server.conf.patch2` does.

Regarding the original issue, that was to suggest that `graylog-server` (The service/app) itself have a default value in the event that the `integrations_scripts_dir` property was missing from `server.conf`. That was rejected but the compromise is to have the package include `integrations_scripts_dir` for the `graylog-server` package.

**Comment by bernd** [comment]
Fixed in https://github.com/Graylog2/fpm-recipes/commit/4ecde4997c37446f88fb8e3999569a72b79dd90b.
