### ISSUE TITLE
Add support for CentOS 7

### ISSUE THREAD

**Issue by bernd** [Graylog2/fpm-recipes#2]
Add support for CentOS 7 operating system.

**Comment by ajanssen** [comment]
+1

**Comment by pkoraca** [comment]
+1

**Comment by joshuascott** [comment]
I can get it working on CentOS 7 by modifying the repo to the following

[graylog]
name=graylog
baseurl=https://packages.graylog2.org/repo/el/6/1.0/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog
skip_if_unavailable = 1
keepcache = 0

Once Graylog sets up an official CentOS 7 repo this can be fixed.

**Comment by linuxprofessor** [comment]
+1
