### ISSUE TITLE
upgrading from 91 to 92 on debian is not .... natural 

### ISSUE THREAD

**Issue by gnafou** [Graylog2/fpm-recipes#21]
when trying to install graylog2-0.92-repository-debian7_latest.deb  package , i had the following error  
`trying to overwrite '/etc/apt/trusted.gpg.d/graylog2-keyring.gpg', which is also in package graylog2-0.91-repository-debian7 1.1.0-1`

i had to remove the graylog2-0.91-repository-debian7 1.1.0-1  and then install the graylog2-0.92-repository-debian7_latest.deb  to be able to get the graylog .92

**Comment by bernd** [comment]
Thanks for the report. The upcoming repo packages for 1.0 will use the replaces flag.
