### ISSUE TITLE
Startup scripts for Ubuntu?

### ISSUE THREAD

**Issue by victorhooi** [Graylog2/fpm-recipes#25]
I've just installed the latest graylog2 packages from the repository on Ubuntu 14.10.

I see that the package has created the following two files in `/etc/init/`:
* /etc/init/graylog2-server.conf
* /etc/init/graylog2-web.conf

However, these scripts don't seem to get picked up by the Upstart commands - e.g. `service --status-all` doesn't list graylog.

Is there something special that needs to be done to get these startup scripts to work with Ubuntu?

**Comment by bernd** [comment]
See #26. Also: we currently support Ubuntu 12.04 and 14.04. (the LTS releases) So maybe something changed in 14.10.
