### ISSUE TITLE
provide 'conflicts' and 'provides' for upgrades

### ISSUE THREAD

**Issue by Finkregh** [Graylog2/fpm-recipes#28]
To allow easy upgrades between major-releases you might want to add 'conflicts' and 'provides' addtitionally to the 'replaces' as described [here](https://www.debian.org/doc/debian-policy/ch-relationships.html#s7.6.2)
:+1:

**Comment by bernd** [comment]
Thank you for the hint.

**Comment by bernd** [comment]
Fixed in 04a45a9859b23a8f390c4472a61a97e8b9e21bc9
