### ISSUE TITLE
No jar files on Ubuntu install

### ISSUE THREAD

**Issue by Depicus** [Graylog2/fpm-recipes#29]
Followed the apt-get method and there doesn't appear to be any jar files installed.

Because the documentation is very light it's hard to tell what should be working, looking at the manual install there should be a graylog-server.jar but a `sudo find / -name "gr*.jar"` only finds /usr/share/graylog-server/graylog.jar - hard to tell if this is the server or not.

There is a graylog-web-interface.graylog-web-interface-1.0.1.jar but again unclear how to use it. 

graylogctl doesn't seem to exist after the install.

And the easy setup fails with ERROR spark.webserver.SparkServer - ignite failed if you have Webmin installed as it uses the same 10000 port.

**Comment by joschi** [comment]
> Because the documentation is very light it's hard to tell what should be working, looking at the manual install there should be a graylog-server.jar

`graylog-server.jar` was renamed to `graylog.jar` because it contains the code for Graylog Radio as well since Graylog 1.0.0. We will update the documentation accordingly.

> There is a graylog-web-interface.graylog-web-interface-1.0.1.jar but again unclear how to use it.

Both Ubuntu DEB packages, `graylog-server` and `graylog-web-interface`, come with an Upstart script to start/stop/restart Graylog and the Graylog web interface.

> graylogctl doesn't seem to exist after the install.

Yes, the function of the `graylogctl` shell script is fulfilled by the Upstart script that comes with the DEB package.

> And the easy setup fails with ERROR spark.webserver.SparkServer - ignite failed if you have Webmin installed as it uses the same 10000 port.

You can change the port for the quick setup application with the `-p` command line parameter.

**Comment by Depicus** [comment]
That's odd because in the syslog I get 

graylog-server main process (3685) terminated with status 1
graylog-server main process ended, respawning
graylog-web main process (3592) terminated with status 255
graylog-web main process ended, respawning

and this is a fresh Ubuntu install with 14.4 and following instructions for apt-get install.

**Comment by bernd** [comment]
Check the logs in `/var/log/graylog-server/server.log` and `/var/log/upstart/graylog-server.log` as well as `/var/log/graylog-web/application.log` and `/var/log/upstart/graylog-web.log`.

Maybe you are missing some configuration parameters.

**Comment by Depicus** [comment]
I am getting 

ERROR [Server] No password secret set. Please define password_secret in your graylog2.conf

But as there was no graylog2.conf I copied over the guts of one from a 0.9 working server. I put it in the same place /etc/graylog2.conf but not sure if this is correct.

Still getting the errors. So....

1. Should there have been a graylog2.conf created on the auto install ?
2. Where should the conf file be located.
