### ISSUE TITLE
Packages for Ubuntu

### ISSUE THREAD

**Issue by martbuo** [Graylog2/fpm-recipes#31]
Hello

I have Ubuntu 14.04.2  and did all steps as documented to obtain Graylog as packages. Though it looks like after "apt-get install graylog-server graylog-web" I do not get full binaries.

root@graylog:~# dpkg-query -L graylog-server
/.
/usr
/usr/share
/usr/share/graylog-server
/usr/share/graylog-server/graylog.jar
/usr/share/graylog-server/bin
/usr/share/graylog-server/bin/graylog-es-timestamp-fixup
/usr/share/graylog-server/lib
/usr/share/graylog-server/lib/sigar
/usr/share/graylog-server/lib/sigar/libsigar-amd64-linux.so
/usr/share/graylog-server/lib/sigar/libsigar-x86-linux.so
/usr/share/graylog-server/plugin
/etc
/etc/default
/etc/default/graylog-server
/etc/init
/etc/init/graylog-server.conf
/etc/graylog
/etc/graylog/server
/etc/graylog/server/server.conf
/etc/graylog/server/log4j.xml
root@graylog:~#

How binaries shall be installed as package in such case ?

Thanks and regards,
Martynas

**Comment by bernd** [comment]
There are no binaries. The `/usr/share/graylog-server/graylog.jar` contains the server code and everything is started via Upstart. (`/etc/graylog/server/server.conf`)

Check the Upstart config on how to invoke the server manually.

**Comment by martbuo** [comment]
Thank you for a clarification. I was looking for files like graylogctl and bin/graylog-web-interface ...



Martynas

**Comment by bernd** [comment]
Yeah, we do not ship those with the packages because there are the init scripts. We might change that in the future though.
