### ISSUE TITLE
Option for latest current minor version?

### ISSUE THREAD

**Issue by chrisdolby** [Graylog2/fpm-recipes#39]
Hi there,

Something I'd really like is to be able to upgrade versions of Graylog between, say, 1.0 and 1.1 - I thought originally that it was taking some time for the versions available through apt on trusty to be updated, but it seems that the repo entries are not just per version of the OS, but also per minor version.

**Comment by bernd** [comment]
Using versioned repositories was a deliberate decision we made to protect users against updating to a new feature release by accident.

Your suggestion is to have something like the following?

```
deb https://packages.graylog2.org/repo/debian/ trusty 1-latest
```

**Comment by bernd** [comment]
Closing this due to lack of feedback. Please re-open if this is still an issue. Thank you!
