### ISSUE TITLE
graylog-1.1-repository-el6_latest does not install newest graylog version

### ISSUE THREAD

**Issue by phermsdorf** [Graylog2/fpm-recipes#40]
Hi,

when using

https://packages.graylog2.org/repo/packages/graylog-1.1-repository-el6_latest.rpm

as install source an 

yum install graylog-server 

only installs version 1.0.2

eg. yum info graylog-server prints:

Name        : graylog-server
Arch        : noarch
Version     : 1.0.2
Release     : 1
Size        : 78 M
Repo        : installed
From repo   : graylog
Summary     : Graylog server
URL        : https://www.graylog.org/
License     : GPLv3
Beschreibung : Graylog server
Name        : graylog-server
Arch        : noarch
Version     : 1.0.2
Release     : 1
Size        : 78 M
Repo        : installed
From repo   : graylog
Summary     : Graylog server
URL        : https://www.graylog.org/
License     : GPLv3
Beschreibung : Graylog server

repo graylog is configured with:
[graylog]
name=graylog
baseurl=https://packages.graylog2.org/repo/el/$releasever/1.1/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog

any hints on this?

thank you

**Comment by bernd** [comment]
Did you have the 1.0 repo package installed before? Maybe a `yum clean all` helps.

**Comment by phermsdorf** [comment]
that fixed it! thank you!
