### ISSUE TITLE
Installation on Debian 8 (Jessie) fails

### ISSUE THREAD

**Issue by jschipper** [Graylog2/fpm-recipes#41]
When installing the graylog-server on debian 8 (jessie) I get the following error:

/var/lib/dpkg/info/graylog-server.postinst: 33: /var/lib/dpkg/info/graylog-server.postinst: systemctl: not found

on #graylog BManojlovic mentioned, this could be because of a too young systemd.

**Comment by joschi** [comment]
Just for completeness: `systemctl` is part of the [`systemd` package in Debian 8.0 (Jessie)](https://packages.debian.org/search?searchon=contents&keywords=systemctl&mode=path&suite=jessie) and `systemd` is the [default init system in Debian 8.0 (Jessie)](https://www.debian.org/releases/jessie/amd64/release-notes/ch-whats-new.en.html#systemd) so the `systemctl` binary should exist on a vanilla Jessie installation.

**Comment by bernd** [comment]
I just tried to reproduce this with a [Debian 8.1 Vagrant box](https://vagrantcloud.com/box-cutter/boxes/debian81), no luck. It works fine. As @joschi said, systemd is the default init system in Debian since 8.0, so systemctl should be there.

**Comment by jschipper** [comment]
Interestingly, it wasn't on my system, I installed from url using the Debian template from Citrix XenServer6.5, aptitude showed the following:
root@srv-log-01:~# aptitude search systemd
p   dh-systemd                                                - debhelper-Erweiterung zur Behandlung von systemd-Dateien           
p   golang-go-systemd-dev                                     - Go client bindings for systemd socket activation, journal and dbus 
p   libghc-libsystemd-journal-dev                             - Haskell bindings to libsystemd-journal                             
v   libghc-libsystemd-journal-dev-1.1.0-1bf09                 -                                                                    
p   libghc-libsystemd-journal-doc                             - Haskell bindings to libsystemd-journal; documentation              
p   libghc-libsystemd-journal-prof                            - Haskell bindings to libsystemd-journal; profiling libraries        
v   libghc-libsystemd-journal-prof-1.1.0-1bf09                -                                                                    
pi  libpam-systemd                                            - System- und Diensteverwaltung - PAM-Modul                          
p   libsystemd-daemon-dev                                     - Hilfsbibliothek für systemd (Übergangspaket)                       
p   libsystemd-daemon0                                        - Hilfsbibliothek für systemd (überholt)                             
p   libsystemd-dev                                            - Hilfsbibliothek für systemd - Entwicklungsdateien                  
p   libsystemd-id128-0                                        - systemd-Hilfsbibliothek für 128-Bit-IDs (überholt)                 
p   libsystemd-id128-dev                                      - Hilfsbibliothek für systemd für 128-Bit-IDs (Übergangspaket)       
p   libsystemd-journal-dev                                    - Hilfsbibliothek für systemd-Journal (Übergangspaket)               
p   libsystemd-journal0                                       - systemd - Bibliothek für den Protokolldienst (überholt)            
p   libsystemd-login-dev                                      - Login-Hilfsbibliothek für systemd (Übergangspaket)                 
p   libsystemd-login0                                         - Login-Hilfsbibliothek für systemd (überholt)                       
i A libsystemd0                                               - Hilfsbibliothek für systemd                                        
p   live-config-systemd                                       - Live System Configuration Components (systemd backend)             
p   python3-systemd                                           - Python-3-Anbindungen für systemd                                   
pB  systemd                                                   - System- und Diensteverwaltung                                      
p   systemd-cron                                              - systemd units to provide minimal cron daemon functionality         
p   systemd-dbg                                               - System- und Diensteverwaltung (Debugsymbole)                       
p   systemd-gui                                               - transitional package for systemd-ui                                
i A systemd-shim                                              - shim for systemd                                                   
pB  systemd-sysv                                              - System- und Diensteverwaltung - Links für SysV                     
p   systemd-ui    

I installed systemd, now it works... Thanks for your help.

**Comment by bernd** [comment]
Great to hear! Closing this.
