### ISSUE TITLE
Graylog Collector for CentOS 6?

### ISSUE THREAD

**Issue by ludakhris** [Graylog2/fpm-recipes#42]
I couldn't locate a collector RPM for Cent OS 6 is there one available?

**Comment by joschi** [comment]
We currently only provide official Graylog Collector packages for CentOS 7 (see http://docs.graylog.org/en/1.1/pages/collector.html#operating-system-packages) but we'll think about supporting other Linux distributions as well if there's some demand for it.

**Comment by ludakhris** [comment]
Is there a way I can compile or create a centos 6 version of the collector?

On Friday, July 24, 2015, Jochen Schalanda <notifications@github.com> wrote:

> We currently only provide official Graylog Collector packages for CentOS 7
> (see
> http://docs.graylog.org/en/1.1/pages/collector.html#operating-system-packages)
> but we'll think about supporting other Linux distributions as well if
> there's some demand for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Graylog2/fpm-recipes/issues/42#issuecomment-124400116>
> .
>


-- 
*"I rather be hated for who I am than to be loved for who I'm not." *
*"If you think I'm talking about you...I probably am." ~Chow*

**Comment by joschi** [comment]
@ludakhris You can simply install it manually. See http://docs.graylog.org/en/1.1/pages/collector.html#manual-setup for details.

**Comment by bernd** [comment]
@ludakhris We will create a OS package for CentOS 6 soon.

**Comment by justyns** [comment]
I would also like to see an official centos6 rpm/repo for the collector.

**Comment by pinkeen** [comment]
seconded

**Comment by libby2cm** [comment]
thirded? :)

**Comment by tece81** [comment]
fourthed.

**Comment by leonkyneur** [comment]
fifthed.

**Comment by longwa** [comment]
Looks like the recipes already has CentOS 6 support but it's commented out. I also see Docker support for it. Is it just broken or can we use fpm to build the package manually?

**Comment by longwa** [comment]
Ok, I was able to build a usage package for CentOS6 using their vagrant/docker support with modifications in my owned fork (https://github.com/longwa/fpm-recipes).

The main issue was that the fpm recipe is missing a proper init.d script for CentOS and proper post-install scripts. I added a pretty generic (and probably not the greatest) init.d/graylog-collector that seems to work fine for me on 6.7.

After you install, you will need to create a working config in /etc/graylog/collector/collector.conf before the service will start.

You can download my CentOS 6 RPM here until they create proper support:
https://bintray.com/artifact/download/longwa/rpm/graylog-collector-0.4.1-1.noarch.rpm

**Comment by joschi** [comment]
@longwa Awesome! Feel free to file a pull request for CentOS 6 support in this repository.

**Comment by alexkipkalo** [comment]
What do you think abut Amazon Linux AMI support ?

**Comment by alankis** [comment]
What is estimated time when collector for CentOS 6 will be avaliable? Thanks

**Comment by joschi** [comment]
@alankis There's no planned release date of the CentOS 6 packages for the Graylog Collector. In the meantime you can use the third-party package built by @longwa.

**Comment by danlsgiga** [comment]
+1 to have a supported CentOS 6 package for the collector!

**Comment by mlandewers** [comment]
+1 For a CentOS 6 collector package

**Comment by bernd** [comment]
The collector is deprecated in favor of the collector-sidecar. I am closing this.
