### ISSUE TITLE
Why not just make the RPMs easily available?

### ISSUE THREAD

**Issue by RobinAllen** [Graylog2/fpm-recipes#43]
I have to install the 'repository' into Yum, using an RPM, and THEN I can use Yum with that repository definition to go back over the Interwebs to download the actual RPMs.

But what if my server is in a closed, locked down environment?  It's not going to have permission to be able to reach out to a repository on the public Interwebs to pull those RPMs down on 80 or 443.

Any other piece of software I'd just pull the few RPMs I need, and deploy them how I see fit. Copy them onto the closed server which needs them, and deploy them manually, or push them with a remote deployment tool. 

OK, so I can play with the manual installation method instead, but really why can't I just have directory listings open on the repository, and none of this amazon signature nonsense, and just download the RPMs?

**Comment by bernd** [comment]
As documented in our [OS package docs](http://docs.graylog.org/en/1.1/pages/installation/operating_system_packages.html) you can use https://packages.graylog2.org/ to browse and download the RPM packages manually.

I hope that helps.
