### ISSUE TITLE
Installation not working  

### ISSUE THREAD

**Issue by varazir** [Graylog2/fpm-recipes#45]
Hi, 

I followed this:
 wget https://packages.graylog2.org/repo/packages/graylog-collector-latest-repository-ubuntu14.04_latest.deb
$ sudo dpkg -i graylog-collector-latest-repository-ubuntu14.04_latest.deb
$ sudo apt-get install apt-transport-https
$ sudo apt-get update
$ sudo apt-get install graylog-collector

and this 
$ bin/graylog-collector run -f ../config/collector.conf

But it failed due to there are no binary found with that name

I did a "find / *graylog*"
and found only this
graylog
graylog/collector
graylog/collector/collector.conf~
graylog/collector/log4j2.xml
graylog/collector/collector.conf
graylog/collector/collector-id

Removed the pkg and installed it, same result

**Comment by bernd** [comment]
If you install the collector via OS package on Ubuntu you have to configure the collector in `/etc/graylog/collector/collector.conf` and start it via upstart. (`sudo start graylog-collector`)

I updated our [collector documentation](http://docs.graylog.org/en/1.1/pages/collector.html) to make this clear.
