### ISSUE TITLE
Problem to start on Ubuntu 15.04

### ISSUE THREAD

**Issue by varazir** [Graylog2/fpm-recipes#46]
I know it supports 14.04 but some of us is running 15.04
15,04 doesn't have "start" so I tried 

sudo service graylog-collector and  sudo systemctl start graylog-collector
Failed to start graylog-collector.service: Unit graylog-collector.service failed to load: No such file or directory.

But got the same error. I'm missing something in the setup I should do? 

TIA
Daniel

**Comment by joschi** [comment]
Ubuntu 15.04 switched the default init system from Upstart to systemd (see https://wiki.ubuntu.com/VividVervet/ReleaseNotes#Boot_and_service_management). We currently only provide Upstart scripts in our Ubuntu packages (and generally only support LTS releases (see https://wiki.ubuntu.com/LTS).

This being said, pull requests to add systemd unit files to the Ubuntu packages are welcome.

**Comment by bernd** [comment]
Graylog packages which support systemd and newer Ubuntu releases will be released with the upcoming Graylog 2.0.
