### ISSUE TITLE
No graylogctl in the CentOS 7 RPM

### ISSUE THREAD

**Issue by varnav** [Graylog2/fpm-recipes#47]
Hello!

I've installed Graylog 1.1.6 from CentOS 7 RPM and I see no **graylogctl** tool at all.

What is the correct way to start graylog server and graylog web UI in CentOS 7?

**Comment by joschi** [comment]
The CentOS 7 RPM comes with unit files for systemd (the default init system used by that Linux distribution). You can simply start Graylog with `systemctl start graylog-server` and `graylog-web`.
