### ISSUE TITLE
Wrong repo for Debian8 (trusty instead jessie)

### ISSUE THREAD

**Issue by przemas75** [Graylog2/fpm-recipes#49]
Did steps according to http://docs.graylog.org/en/latest/pages/installation/operating_system_packages.html#debian-8
After that i had additional repo for graylog, however wrong debian verision in the file.

Initially i had trusty in /etc/apt/sources.list.d/graylog.list and had manually change to jessie, now it looks:
```
cat /etc/apt/sources.list.d/graylog.list
deb https://packages.graylog2.org/repo/debian/ jessie 1.2
```
Now, system install graylog with proper systemd initializaiont. Before that, it was not.

**Comment by przemas75** [comment]
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"


lsb_release -sc
jessie

**Comment by przemas75** [comment]
https://github.com/przemas75/fpm-recipes/commit/cb848ee04e61ddf97c937515362f3ec91d2b6900

**Comment by joschi** [comment]
`trusty` is referring to Ubuntu 14.04 LTS (Trusty Tahr) and should only be in the release file for that Linux distribution.

@przemas75 Are you sure that you've downloaded and installed the correct DEB package for your distribution, i. e. https://packages.graylog2.org/repo/packages/graylog-1.2-repository-debian8_latest.deb and not https://packages.graylog2.org/repo/packages/graylog-1.2-repository-ubuntu14.04_latest.deb?

**Comment by przemas75** [comment]
You are totally right, i have installed ubuntu14.04 deb on debian8.
Sorry for confusion.
