### ISSUE TITLE
Set open files limit for upstart jobs

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/fpm-recipes#52]
We had an issue with our graylog-server nodes refusing to start due to "Too many open files.

The easiest way to avoid that situation is to include the following into /etc/init/graylog-server.conf :
limit nofile 64000 64000

**Comment by bernd** [comment]
Thank you for the report. Fixed in the upcoming Graylog 1.3 release.

**Comment by henrikjohansen** [comment]
<3
