### ISSUE TITLE
Is there a prebuild RPM for graylog2-web-interface-1.2.2

### ISSUE THREAD

**Issue by willsc** [Graylog2/fpm-recipes#54]
Is there a prebuild RPM for graylog2-web-interface-1.2.2 and  I don't mean the repo rpm. I'm unable to build this due to dependencies.

**Comment by joschi** [comment]
@willsc Yes, see http://docs.graylog.org/en/1.2/pages/installation/operating_system_packages.html#centos-7 and https://packages.graylog2.org/
