### ISSUE TITLE
Package graylog-web /graylog-server is not available,

### ISSUE THREAD

**Issue by khalil1608** [Graylog2/fpm-recipes#56]
Hello,

When i try to install graylog-web and graylog-server i have two errors : 

Package graylog-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package graylog-web is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'graylog-server' has no installation candidate
E: Package 'graylog-web' has no installation candidate

Any Idea ? 

Thanx

**Comment by joschi** [comment]
@khalil1608 How exactly did you set up the repository? How exactly are you trying to install the `graylog-server` and `graylog-web` packages?

**Comment by khalil1608** [comment]
I just follow the tutorial for install graylog for debian 8.

http://docs.graylog.org/en/1.3/pages/installation/operating_system_packages.html

$ wget https://packages.graylog2.org/repo/packages/graylog-1.3-repository-debian8_latest.deb
$ sudo dpkg -i graylog-1.3-repository-debian8_latest.deb
$ sudo apt-get install apt-transport-https
$ sudo apt-get update
$ sudo apt-get install graylog-server graylog-web

**Comment by bernd** [comment]
I am unable to reproduce this on Debian 8. Please re-open if you still have this problem and include the complete output for the commands. Thank you!

**Comment by azzeddinefaik** [comment]
I got the same error I try to install graylog2 in separate server :  
graylog-server  
graylog-web 
but I can not found graylog-web package
