### ISSUE TITLE
Problem start Graylog Web Interface

### ISSUE THREAD

**Issue by khalil1608** [Graylog2/fpm-recipes#57]
Hello,

I manually installed graylog in my server and I have a problem when I start it.

When I lunch that command : I manually installed : bin/graylog-web-interface -Djava.net.preferIPv4Stack=true -Dhttp.port=9050 &

I have the error 
[error] o.g.r.l.ApiClient - Connexion denied: /127.0.0.1:12900

Any Idea ?

Thanks

**Comment by joschi** [comment]
@khalil1608 Is graylog-server listening on the given interface (`127.0.0.1:12900`)?

**Comment by khalil1608** [comment]
Yes..

**Comment by joschi** [comment]
@khalil1608 The web interface doesn't seem to be able to connect to it. What's the output of the following command on the system running graylog-web-interface?
```
curl -i http://127.0.0.1:12900/
```

**Comment by bernd** [comment]
Closing this, please re-open if you have new information. Thank you!
