### ISSUE TITLE
Prepare DEB repository for SHA-1 removal

### ISSUE THREAD

**Issue by joschi** [Graylog2/fpm-recipes#58]
Fetching the DEB package repository via `apt-get` (APT 1.1) using Debian SID results in the following error message:
```
E: Failed to fetch https://packages.graylog2.org/repo/debian/dists/stable/Release  No Hash entry in Release file /var/lib/apt/lists/partial/packages.graylog2.org_repo_debian_dists_stable_Release which is considered strong enough for security purposes
```

This is probably caused by the removal of SHA-1 hashes for validating repositories and packages: https://wiki.debian.org/Teams/Apt/Sha1Removal

Refs rcrowley/freight#66

Using the (modernized) fork of freight might help: https://github.com/freight-team/freight

**Comment by bernd** [comment]
Thank you! This has been fixed, the current repos support the new hashing algo.
