### ISSUE TITLE
Graylog internal log appender missing from packaged `log4j.xml`

### ISSUE THREAD

**Issue by amerkel2** [Graylog2/fpm-recipes#59]
The internal log appender is missing from the packaged `log4j.xml` file, although the example config advises not to disable it (cf. https://github.com/Graylog2/graylog2-server/blob/1.3/graylog2-bootstrap/src/main/resources/log4j.xml#L13).

**Comment by joschi** [comment]
@amerkel2 Thanks for reporting this! It seems like we've missed that one.

The missing appender will be added in the next package release.
