### ISSUE TITLE
documentation: change order of commands for debian/ubuntu

### ISSUE THREAD

**Issue by kgyrtkirk** [Graylog2/fpm-recipes#60]
hello,

on the site: http://docs.graylog.org/en/1.3/pages/installation/operating_system_packages.html
i would recommend to move the 'sudo apt-get install apt-transport-https' before the 'dpkg -i'
because the package itself installs an https apt source - possibly breaking 'apt-get update' functionality and if someone has an outdated package list; cant update to install the missing transport (like me today ;)

cheers

**Comment by bernd** [comment]
Thank you, good catch! :+1: The documentation has been adjusted.
