### ISSUE TITLE
Wrong directory on CentOS / RHEL Repository

### ISSUE THREAD

**Issue by rikatz** [Graylog2/fpm-recipes#65]
The repository rpm (https://packages.graylog2.org/repo/packages/graylog-2.0-repository_latest.rpm) is generating the file /etc/yum.repos.d/graylog.repo with the following baseurl: https://packages.graylog2.org/repo/el/stable/2.0/$basearch/

While the right baseurl is https://packages.graylog2.org/el/stable/2.0/$basearch/

Also it's reporting that the repomd.xml file is damaged :)

**Comment by rikatz** [comment]
Corrected on PR #66

**Comment by joschi** [comment]
Closing this issue in tandem with #66.
