### ISSUE TITLE
Graylog Server RPM - file descriptor limit

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/fpm-recipes#72]
## Expected Behavior

Installation of the RPM should result in the same file descriptor limit being used as other packages (see e8e0549ed514d29b31e0f2d573a13ef5d5290a13).

## Current Behavior

The default file descriptor limit (4096 in my case) is used when the RPM is used for Graylog Server installation.

## Possible Solution

Add `ulimit -n 64000` inside the `start` function (before the `daemon` call) in "fpm-recipes/recipes/graylog-server/files/rpm/init.d".

## Steps to Reproduce (for bugs)

1. Have a CentOS/RHEL system
2. Install a Graylog Server RPM (e.g. "graylog-server-2.0.3-1.noarch.rpm")
3. Verify the `graylog-server` service is started
4. Get the current limits (`sudo cat /proc/graylog_server_PID/limits`) and note "Max open files" is the default (e.g. 4096)
5. Stop the `graylog-server` service
6. Insert `ulimit -n 64000` as the first line of the `start` function in "/etc/init.d/graylog-server"
7. Start the `graylog-server` service
8. Get the current limits (`sudo cat /proc/graylog_server_PID/limits`) and note "Max open files" is now 64000

## Context

We were seeing "Too many open files" in the Graylog Server "server.log" and wanted to increase the limit to rule that out.

## Your Environment
* Graylog Version: 2.0.3
* Elasticsearch Version:  2.2.0
* MongoDB Version:  2.6.12
* Operating System:  Red Hat Enterprise Linux Server release 6.7
* Browser version:  Firefox 48

**Comment by bernd** [comment]
This will be fixed in the upcoming Graylog 2.1 release. Thank you for the report!
