### ISSUE TITLE
Gray external messages issue.

### ISSUE THREAD

**Issue by bkrajesh** [Graylog2/fpm-recipes#74]
I have configured the sidecar with nxlog. but Input node running fine in graylog server GUI. but I am not unable to find the message. 

note: I  unable to create the cluster from my graylog GUI, because of option not showing.

could you  please help me on this. or arrange the one meeting with my team, it' really helpful to us.

(Note: if you can arrange the meeting my company will take license from end.)

I am waiting for your response.

**Comment by mariussturm** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
