### ISSUE TITLE
Install from Debian apt repo -- Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)

### ISSUE THREAD

**Issue by stantona** [Graylog2/fpm-recipes#83]
I'm not sure whether this is the correct repository to file this issue, but this relates to installing `graylog-server` from the Debian sources. After setting up the apt repository according to the [documentation](http://docs.graylog.org/en/2.4/pages/installation/operating_system_packages.html#deb-apt), I'm encountering a problem when the repository is updated.

After doing a `apt-get update` on Debian 9, I get the following:
```
Get:15 http://packages.graylog2.org/debian stable InRelease [1,926 B]
Err:15 http://packages.graylog2.org/debian stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```

I notice that requests made to the packages endpoint always seem to result in a 200 result, regardless of whether the file exists. E.g, for `InRelease` (which doesn't exist):
```
$ wget --server-response -qO- https://packages.graylog2.org/debian/dists/stable/InRelease
  HTTP/1.1 200 OK
  Server: Cowboy
  Connection: keep-alive
  Date: Tue, 29 May 2018 00:10:23 GMT
  Content-Type: text/html
  Vary: Accept-Encoding
  Content-Length: 2164
  Via: 1.1 vegur
```
For `Release`:
```
$ wget --server-response -qO- https://packages.graylog2.org/debian/dists/stable/Release
  HTTP/1.1 200 OK
  Server: Cowboy
  Connection: keep-alive
  Date: Tue, 29 May 2018 00:10:23 GMT
  Content-Type: text/html
  Vary: Accept-Encoding
  Content-Length: 2164
  Via: 1.1 vegur
```

The body of the request is HTML with the Graylog header with an empty list of results.

I'm wondering whether these requests are not redirecting as they should? For e.g, should `InRelease` redirect (302) to `Release`, which in turn redirects to the file on S3? Making the request in the browser by following the hyperlinks works this way.

**Comment by joschi** [comment]
@stantona You're probably using the wrong URI in the package.list for the Graylog package repository.

See http://docs.graylog.org/en/2.4/pages/installation/operating_system_packages.html#manual-repository-installation for the correct URI.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
