### ISSUE TITLE
Ubuntu-18.04 defaults to openjdk-10

### ISSUE THREAD

**Issue by jhaar** [Graylog2/fpm-recipes#86]
I followed the instructions on 

http://docs.graylog.org/en/3.0/pages/installation/os/ubuntu.html

After installing everything and setting passwords/etc, I started graylog-server but got the following error

Jan 18 06:17:13 xx graylog-server[10990]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Jan 18 06:17:13 xx  graylog-server[10990]: Unrecognized VM option 'UseParNewGC'
Jan 18 06:17:13 xx  graylog-server[10990]: Error: Could not create the Java Virtual Machine.
Jan 18 06:17:13 xx graylog-server[10990]: Error: A fatal exception has occurred. Program will exit.

Obviously what had happened is that I already had openjdk-10 installed and so "/usr/bin/java" was pointing at that instead of the openjdk-8-jre-headless I had installed later as part of this graylog install.

I assume getting graylog to support newer jdks is non-trivial, so maybe there should be some comment on the Ubuntu doc that if people already have other jdk's installed, they need to hardwire the JAVA setting in /etc/default/graylog-server? ie

JAVA=/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java

that fixed it for me. Thanks!

**Comment by bernd** [comment]
@jhaar Thank you for the report! We will document this!

**Comment by mpfz0r** [comment]
We have no known issues when running with newer java versions anymore.
Closing this.
